### ISSUE TITLE
Resol Deltasol SLT supported ?

### ISSUE THREAD

**Issue by faronov** [tripplet/vbus-collector#1]
I have Resol Deltasol SLT controller, and connect USB port to the raspberry pi
build your project and connect it to usb port
but receive strange result
first question why system time is showed 2 different time
second question , data looks very strange 
this device is not supported ? I can do something for improve correct data reporting ?

System time:04:46, Sensor1 temp:557.2C, Sensor2 temp:874.4C, Sensor3 temp:43.7C, Sensor4 temp:40.0C, Pump speed1:98%, Pump speed2:1%, Hours1:0, Hours2:0

System time:440:09, Sensor1 temp:-2421.9C, Sensor2 temp:6.0C, Sensor3 temp:12.9C, Sensor4 temp:0.0C, Pump speed1:236%, Pump speed2:1%, Hours1:48585, Hours2:0

System time:459:17, Sensor1 temp:-793.6C, Sensor2 temp:6.2C, Sensor3 temp:13.5C, Sensor4 temp:0.0C, Pump speed1:3%, Pump speed2:2%, Hours1:50637, Hours2:0

System time:04:46, Sensor1 temp:557.5C, Sensor2 temp:874.4C, Sensor3 temp:43.7C, Sensor4 temp:40.0C, Pump speed1:98%, Pump speed2:1%, Hours1:0, Hours2:0

System time:04:46, Sensor1 temp:557.6C, Sensor2 temp:874.4C, Sensor3 temp:43.7C, Sensor4 
temp:40.0C, Pump speed1:98%, Pump speed2:1%, Hours1:0, Hours2:0

System time:04:46, Sensor1 temp:557.7C, Sensor2 temp:874.4C, Sensor3 temp:43.7C, Sensor4 temp:40.0C, Pump speed1:98%, Pump speed2:1%, Hours1:0, Hours2:0

System time:04:46, Sensor1 temp:557.8C, Sensor2 temp:874.4C, Sensor3 temp:43.7C, Sensor4 temp:40.0C, Pump speed1:98%, Pump speed2:1%, Hours1:0, Hours2:0

**Comment by tripplet** [comment]
Hi. 
Thats strange, I'm not sure the Deltasol SLT gives out the VBUS protocol directly via USB.
It looks like the device is way more capable, sadly I could not find any documentation online about the USB port of the DeltaSol SLT.

This project assumes that virtual serial port is just a mapper to the VBUS protocol described by RESOL
e.g. https://hobbyelektronik.org/w/images/0/04/VBus-Protokollspezifikation.pdf

There are lots of VBUS decoders online maybe you can try another one just to make sure it is a problem of the specific code in this project.

e.g. https://github.com/danielwippermann/resol-vbus

**Comment by faronov** [comment]
Thanks
this project https://github.com/danielwippermann/resol-vbus give me the right result
