### ISSUE TITLE
Non Resol USB adapter

### ISSUE THREAD

**Issue by craggyh** [tripplet/vbus-collector#2]
Does this work with a non Resol USB adapter?
I have an RS232 to USB adapter and can see in Resol Service Center that it is capturing all the raw hex data and I was hoping this script could connect to the same USB Serial adapter and decode the data?

**Comment by tripplet** [comment]
It think RS232 will not work as VBUS is more like RS485, see: https://hobbyelektronik.org/w/images/0/04/VBus-Protokollspezifikation.pdf, chapter Hardware.
I think I read somewhere that an RS485 adapter might work but I'm no expert on that:
See https://groups.google.com/forum/#!searchin/resol-vbus/rs485%7Csort:date/resol-vbus/sBsTSZ6bw7Y/HBrdR6uJBAAJ
